### ISSUE TITLE
有木有人，有兴趣把这个框架盘活，维护起来。交给社区日常维护。

### ISSUE THREAD

**Issue by aohanhongzhi** [biezhi/blade#428]
目前这个框架官网也没有了。
还有很多的bug没有解决。

如果有人和我一样有兴趣的话，我们可以组织下，搞起来。

**Comment by os7blue** [comment]
作者被一位女施主收了。

**Comment by chlch** [comment]
> 目前这个框架官网也没有了。 还有很多的bug没有解决。
> 
> 如果有人和我一样有兴趣的话，我们可以组织下，搞起来。

举几个bug列一下，跑个demo目前还感受不出来。

**Comment by YihaoShen** [comment]
> 这个框架现在真的有点可惜了，blade确实是一个很不错的框架。

**Comment by auula** [comment]
大师兄我来接管项目。

**Comment by aohanhongzhi** [comment]
> 大师兄我来接管项目。

你有项目权限了？还是联系了作者？

**Comment by hellokaton** [comment]
开始维护，敬请期待新版本。

**Comment by caoli5288** [comment]
确实可惜，4年没更新，轻量框架已经转投javalin了，

**Comment by hellokaton** [comment]
> 确实可惜，4年没更新，轻量框架已经转投javalin了，

是这样的，目前维护已有功能，确保没有使用上的 bug。不维护很大程度也是因为市面的框架相似度都比较高，如果没有突出特色的话意义不是很大，web 框架目前都很成熟的，该有的基本都差不多。比如响应式可以用 `vert.x`，简洁的可以用 `sparkjava`，需要依赖注入可以用 `Google Guice`
